DROP TABLE IF EXISTS StudentExercise;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Exercise;
DROP TABLE IF EXISTS Instructor;
DROP TABLE IF EXISTS Cohort;


CREATE TABLE Cohort (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	CohortName VARCHAR (50) NOT NULL
);

CREATE TABLE Student (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    FirstName VARCHAR(25) NOT NULL,
	LastName VARCHAR(25) NOT NULL,
	Slack VARCHAR(25) NOT NULL,
	CohortId INT NOT NULL,
	CONSTRAINT FK_StudentCohort FOREIGN KEY(CohortId) REFERENCES Cohort(Id)
);

CREATE TABLE Instructor (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    FirstName VARCHAR(25) NOT NULL,
	LastName VARCHAR(25) NOT NULL,
	Slack VARCHAR(25) NOT NULL,
	CohortId INT NOT NULL,
	InstructorType VARCHAR(50) NOT NULL,
	CONSTRAINT FK_InstructorCohort FOREIGN KEY(CohortId) REFERENCES Cohort(Id)
);

CREATE TABLE Exercise (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    ExerciseName VARCHAR(50) NOT NULL,
	ExerciseLanguage VARCHAR(50) NOT NULL
);

CREATE TABLE StudentExercise (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	StudentId INT NOT NULL,
	ExerciseId INT NOT NULL,
	CONSTRAINT FK_StudentId FOREIGN KEY(StudentId) REFERENCES Student(Id),
	CONSTRAINT FK_ExerciseId FOREIGN KEY(ExerciseId) REFERENCES Exercise(Id)
);

